submit.temporarilyOffline=Bring back online
submit.not.temporarilyOffline=Mark temporarily offline
submit.updateOfflineCause=Update offline reason
title=Set {0} Offline Reason
blurb=You can set or update the reason why this node is offline, so that others can see why:
submit=Update reason
