tasks:
  - init: |
      mvn -B -T 1C -DskipTests package
    command: |
      mvn -pl war jetty:run -Djetty.http.port=8080 -DskipTests
    name: Run

ports:
  - port: 8080
    onOpen: open-preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - "org.jetbrains.plugins.stapler"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml

image:
  file: .gitpod/Dockerfile
