tasks:
  - init: |
      mvn -am -pl war,bom -P quick-build clean install
    command: |
      mvn -pl war jetty:run -Dhost=0.0.0.0
    name: Run
  - command: gp ports await 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins/
    name: Preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack

image:
  file: .gitpod/Dockerfile
