#!/bin/bash -xe
# The MIT License
# 
# Copyright (c) 2004-2009, Sun Microsystems, Inc., Kohsuke Kawaguchi
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


#
# publish Hudson javadoc and deploy that into the java.net CVS repository
# 

# make sure we have up-to-date copy so that the commit won't fail later
pushd ../../../www/javadoc
svn revert -R .
svn update
popd

cp -R target/checkout/target/site/apidocs/* ../../../www/javadoc

cd ../../../www/javadoc

# remove timestamp as this creates unnecessary revisions for javadoc files
find . -name "*.html" | xargs perl -p -i.bak -e "s|-- Generated by javadoc .+--|-- --|"
find . -name "*.html" | xargs perl -p -i.bak -e "s|<META NAME=\"DATE\" CONTENT=\"....-..-..\">||"
find . -name "*.bak" | xargs rm

# add files that are new
svn add $(svn status | grep "^?" | cut -d " " -f2-) .
svn commit -m "commiting javadoc"

