#!/bin/sh -e
# convert an svg file to a png file
# Usage: cat some.svg | svg2png ...options... > some.png
#
# option: -w width -h height

tmpA=/tmp/svg2pngA$$
tmpB=/tmp/svg2pngB$$

cat > $tmpA
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -z -e "$tmpB" "$@" "$tmpA" 1>&2
cat $tmpB
rm $tmpA $tmpB
