Document: hudson
Title: Debian hudson Manual
Author: <insert document author here>
Abstract: This manual describes what hudson is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hudson/hudson.sgml.gz

Format: postscript
Files: /usr/share/doc/hudson/hudson.ps.gz

Format: text
Files: /usr/share/doc/hudson/hudson.text.gz

Format: HTML
Index: /usr/share/doc/hudson/html/index.html
Files: /usr/share/doc/hudson/html/*.html

  
