#!/bin/bash

JENKINS_PLIST="/Library/LaunchDaemons/org.jenkins-ci.plist"

# Because PackageMaker just copies the components, we need to fix the permissions
chown root:admin ${JENKINS_PLIST}
chmod 644 ${JENKINS_PLIST}
chown -R daemon:daemon /Users/Shared/Jenkins

# Load and start the launch daemon
/bin/launchctl load ${JENKINS_PLIST}
/bin/launchctl start org.jenkins-ci
