blurb = The URL you''re trying to access requires that requests be sent using POST (like a form submission). \
  The button below allows you to retry accessing this URL using POST. \
  URL being accessed:
warning = Clicking the button below will perform this action using your current session and permissions. \
  Only proceed if you intended to perform this action, arriving at this page, even from a link within Jenkins, \
  does not mean the action is safe or expected.